### ISSUE TITLE
putDirectory will omit file in some case

### ISSUE THREAD

**Issue by calledT** [steelbrain/node-ssh#129]
My local dir have two files, e.g.  `a.js` and `b.js`.

My remote dir have multiple empty level, e.g. `/foo/bar`. 

use putDirectory only one file will upload to `/foo/bar` first time.

tick function has error message:
```bash
{ Error: Failure
    at SFTPStream._transform (...\node_modules\ssh2-streams\lib\sftp.js:410:27)
    at SFTPStream.Transform._read (_stream_transform.js:190:10)
    at SFTPStream._read (...\node_modules\ssh2-streams\lib\sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at SFTPStream.Writable.write (_stream_writable.js:294:11)
    at Channel.ondata (_stream_readable.js:666:20)
    at Channel.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12) code: 4, lang: '' }
```

**Comment by TMaize** [comment]
> My local dir have two files, e.g. `a.js` and `b.js`.
> 
> My remote dir have multiple empty level, e.g. `/foo/bar`.
> 
> use putDirectory only one file will upload to `/foo/bar` first time.
> 
> tick function has error message:
> 
> ```shell
> { Error: Failure
>     at SFTPStream._transform (...\node_modules\ssh2-streams\lib\sftp.js:410:27)
>     at SFTPStream.Transform._read (_stream_transform.js:190:10)
>     at SFTPStream._read (...\node_modules\ssh2-streams\lib\sftp.js:181:15)
>     at SFTPStream.Transform._write (_stream_transform.js:178:12)
>     at doWrite (_stream_writable.js:410:12)
>     at writeOrBuffer (_stream_writable.js:394:5)
>     at SFTPStream.Writable.write (_stream_writable.js:294:11)
>     at Channel.ondata (_stream_readable.js:666:20)
>     at Channel.emit (events.js:182:13)
>     at addChunk (_stream_readable.js:283:12) code: 4, lang: '' }
> ```

concurrency:1 is OK

**Comment by paragraff** [comment]
same bug as [this](https://github.com/steelbrain/node-ssh/issues/127)

**Comment by steelbrain** [comment]
Default concurrency now is `1`
