### ISSUE TITLE
Error: Cannot write to middle of file. Only append is allowed.

### ISSUE THREAD

**Issue by ejbp** [steelbrain/node-ssh#220]
I have a random behaviour when putting a file into an sftp server. Sometimes I receive this error:

```
(node:53308) UnhandledPromiseRejectionWarning: Error: Cannot write to middle of file. Only append is allowed.
    at SFTPStream._transform (/Users/xxx/feeds/node_modules/ssh2-streams/lib/sftp.js:412:27)
    at SFTPStream.Transform._read (_stream_transform.js:190:10)
    at SFTPStream._read ((/Users/xxx/feeds/node_modules/ssh2-streams/lib/sftp.js:183:15)
    at SFTPStream.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at SFTPStream.Writable.write (_stream_writable.js:299:11)
    at Channel.ondata (_stream_readable.js:693:20)
    at Channel.emit (events.js:197:13)
    at addChunk (_stream_readable.js:288:12)
```

File size is approximately  390kb . 

code is: 

 ```
  const filepath="/tmp/test.json";
  const filename ="mytest.json";

  await ssh.connect({
    "host": "host.com",
    "port": 19510,
    "privateKey": "/Users/xxxxx/.ssh/id_rsa",
    "passphrase": "xxxx",
 });

  await ssh.putFile(filepath, filename); //this throws the exception
  
  await ssh.dispose();
```

Important to say that the server only have write permissions. We cannot retrieve a file.

**Comment by steelbrain** [comment]
I've just published v7 with an upgraded `ssh2`, please try and report back

**Comment by ejbp** [comment]
Sorry my late reply. 

Unfortunately, the result is the same. 

I found this post https://stackoverflow.com/questions/7928648/write-function-not-using-the-seekp-value (c++) and i give a try by passing on opts argument {mode: 3}, or only {mode: 2} but it didn't work. You can see the modes in the ss2-streams module.

For now I'm using an ugly solution that is setting the chunk size with exactly the same ammount as filesize. As I'm working with "small" files, its working for now. But this is not a final solution.

ex: 
`
ssh.putFile(fromPath, dest, undefined, {fileSize, chunkSize: fileSize});  
`

**Comment by steelbrain** [comment]
I have now made `concurrency` default as `1`
