### ISSUE TITLE
Cannot parse privateKey: Unsupported OpenSSH private key type: ssh-ed25519

### ISSUE THREAD

**Issue by pratikgaikwadhive** [steelbrain/node-ssh#233]
@steelbrain ,

I am getting below error when I trying to connect using keys generated with `ed25519` algorithm.

```
Error: Cannot parse privateKey: Unsupported OpenSSH private key type: ssh-ed25519
        at Client.connect (/opt/hive/services/hive-fabric/node_modules/ssh2/lib/client.js:243:13)
        at Promise (/opt/hive/services/hive-fabric/node_modules/node-ssh/lib/index.js:61:18)
        at new Promise (<anonymous>)
        at Promise.then.config (/opt/hive/services/hive-fabric/node_modules/node-ssh/lib/index.js:35:23)
```

It should be resolved as per [this comment](https://github.com/mscdex/ssh2/issues/352#issuecomment-486511390)

Can you please update the packages and release new version?

**Comment by steelbrain** [comment]
Fixed in v7
