### ISSUE TITLE
"error:failure" on putFile command

### ISSUE THREAD

**Issue by FrancisVila** [steelbrain/node-ssh#312]
I have an error on putFile command where the error message is just "**Failure**" (one word). The connection and getFile commands appear to be working. This is on Ubuntu 16.04.3 LTS.
Here's the connection code with the putfile. The complete error stack follows.

```
const NodeSSH = require('node-ssh');
  node_ssh = new NodeSSH()

  node_ssh.connect({
  host: 'my.remote.host', 
  username: 'uuuuuu',
  password: 'pppppp',
  hostKeys: ['ssh-xxxxxxxx='],
  privateKey: '/path/to/keys/mykey.ppk'
  }).then (function() {
  node_ssh.putFile('/path/to/public/directory/myfile.zip',  '/path/on/remote/server/' )
   .then(function() {
    console.log("The File thing is done")
   }, function(error) {
    console.log("Something's wrong in node_ssh.putFiles60: " + error.message)
    console.log( error)
    })
   }) }
```

```

****Error stack:**** 

{ Error: Failure
    at SFTPStream._transform (/path/to/project/node_modules/node-ssh/node_modules/ssh2-streams/lib/sftp.js:412:27)
    at SFTPStream.Transform._read (_stream_transform.js:190:10)
    at SFTPStream._read (/var/www/confluence_to_zoomin_server/node-react-starter/node_modules/node-ssh/node_modules/ssh2-streams/lib/sftp.js:183:15)
    at SFTPStream.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at SFTPStream.Writable.write (_stream_writable.js:294:11)
    at Channel.ondata (_stream_readable.js:663:20)
    at Channel.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Channel.Readable.push (_stream_readable.js:219:10)
    at SSH2Stream.<anonymous> (/var/www/confluence_to_zoomin_server/node-react-starter/node_modules/node-ssh/node_modules/ssh2/lib/Channel.js:167:15)
    at SSH2Stream.emit (events.js:182:13)
    at parsePacket (/var/www/confluence_to_zoomin_server/node-react-starter/node_modules/node-ssh/node_modules/ssh2-streams/lib/ssh.js:3191:10)
    at SSH2Stream._transform (/var/www/confluence_to_zoomin_server/node-react-starter/node_modules/node-ssh/node_modules/ssh2-streams/lib/ssh.js:701:13) code: 4, lang: '' }
```

**Comment by FrancisVila** [comment]
Nailed it! It's not:
`node_ssh.putFile('/path/to/public/directory/myfile.zip',  '/path/on/remote/server/' )`
but 
`node_ssh.putFile('/path/to/public/directory/myfile.zip',  '/path/on/remote/server/myfile.zip' )`
However, the error message should be more explicit

**Comment by steelbrain** [comment]
Hi @FrancisVila 

Thank you for reporting this. The error messages come from the server. It may not be a good idea to redo error messages in this package as it's out of scope, but we could wrap them around to add some context like `SFTPRequestFailure`. Does that sound like it'll make it more obvious for you?

**Comment by FrancisVila** [comment]
hi @steelbrain ,
Thanks for answering!
I don't quite get what you mean by SFTPRequestFailure... The error came from my expecting the command to work like the copy command in Windows, where you specify 1) the file to copy and 2) the target folder -  unless you want to change the name of the file to move. But I imagine there are all sorts of cases, such as if there are several files or directories to copy, etc. So I can understand it may not be a trivial undertaking.
