### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by dtouffut** [steelbrain/node-ssh#346]
Hello !
First of all I want to tell you that I love your module!
Here is the mistake I come across:
```
(node:20550) UnhandledPromiseRejectionWarning: Error: (SSH) Channel open failure: open failed
    at SSH2Stream.onFailure (/usr/src/app/node_modules/ssh2/lib/client.js:1205:13)
    at Object.onceWrapper (events.js:421:26)
    at SSH2Stream.emit (events.js:314:20)
    at SSH2Stream.EventEmitter.emit (domain.js:486:12)
    at parsePacket (/usr/src/app/node_modules/ssh2-streams/lib/ssh.js:3455:10)
    at SSH2Stream._transform (/usr/src/app/node_modules/ssh2-streams/lib/ssh.js:701:13)
    at SSH2Stream.Transform._read (_stream_transform.js:205:10)
    at SSH2Stream._read (/usr/src/app/node_modules/ssh2-streams/lib/ssh.js:253:15)
    at SSH2Stream.Transform._write (_stream_transform.js:193:12)
    at writeOrBuffer (_stream_writable.js:352:12)
(node:20550) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 12)
```
I run an SSH command in a for loop in an asynchronous function and I don’t understand why I always have this error

**Comment by dtouffut** [comment]
With a catch for my async function, the returned error is :
```
Error: (SSH) Channel open failure: open failed
    at SSH2Stream.onFailure (/usr/src/app/node_modules/ssh2/lib/client.js:1205:13)
    at Object.onceWrapper (events.js:421:26)
    at SSH2Stream.emit (events.js:314:20)
    at SSH2Stream.EventEmitter.emit (domain.js:486:12)
    at parsePacket (/usr/src/app/node_modules/ssh2-streams/lib/ssh.js:3455:10)
    at SSH2Stream._transform (/usr/src/app/node_modules/ssh2-streams/lib/ssh.js:701:13)
    at SSH2Stream.Transform._read (_stream_transform.js:205:10)
    at SSH2Stream._read (/usr/src/app/node_modules/ssh2-streams/lib/ssh.js:253:15)
    at SSH2Stream.Transform._write (_stream_transform.js:193:12)
    at writeOrBuffer (_stream_writable.js:352:12) {
  reason: 'ADMINISTRATIVELY_PROHIBITED',
  lang: ''
}
```

**Comment by steelbrain** [comment]
Hello @dtouffut 

Thanks for the report, this is quite an interesting error you got

Can you please share the code you used that led you to this error?

Thanks

**Comment by vijaypremchandran** [comment]
I am using code like below and getting the same error. I  am new to Nodejs and need help with this error.

const localFolder = `C:\\Users\\${userName}\\Documents\\Programming\\accumFileGen\\accum_test.txt`;


//get the root request and send the HTML form.
app.get('/', (req, res) => {
    res.render("index.ejs");
  })

// catch the send route..
app.post('/sendFile', (req,res) => {
    console.log('catching send file route')
    //connect to the server and put the file in the dir.
    console.log (localFolder);
    
    ssh.connect({
        host: 'xxx.xx.xxx.xx',
        username: userName,
        privateKey: `C:\\Users\\${userName}\\.ssh\\id_rsa`
      })
      .then(function() {
        // Local, Remote
        ssh.putFile(localFolder, 'To path directory').then(function() {
          console.log("The File thing is done")
        }, function(error) {
          console.log("Something's wrong")
          console.log(error)
        })
      })
    res.redirect('/');
})

error message : 
(node:20324) UnhandledPromiseRejectionWarning: Error: Handshake failed: no matching key exchange algorithm
    at makeError (C:\Users\vchandran\Documents\Programming\accumFileGen\node_modules\ssh2\lib\protocol\utils.js:142:15)
    at doFatalError (C:\Users\vchandran\Documents\Programming\accumFileGen\node_modules\ssh2\lib\protocol\utils.js:184:13)
    at handleKexInit (C:\Users\vchandran\Documents\Programming\accumFileGen\node_modules\ssh2\lib\protocol\kex.js:239:12)
    at Protocol.onKEXPayload (C:\Users\vchandran\Documents\Programming\accumFileGen\node_modules\ssh2\lib\protocol\kex.js:1755:14)
    at NullDecipher.decrypt (C:\Users\vchandran\Documents\Programming\accumFileGen\node_modules\ssh2\lib\protocol\crypto.js:617:26)
    at Protocol.parsePacket [as _parse] (C:\Users\vchandran\Documents\Programming\accumFileGen\node_modules\ssh2\lib\protocol\Protocol.js:1993:25)    
    at Protocol.parse (C:\Users\vchandran\Documents\Programming\accumFileGen\node_modules\ssh2\lib\protocol\Protocol.js:292:16)
    at Socket.<anonymous> (C:\Users\vchandran\Documents\Programming\accumFileGen\node_modules\ssh2\lib\client.js:712:21)
    at Socket.emit (events.js:375:28)
    at addChunk (internal/streams/readable.js:290:12)

I am using the same code that is provided by you. Thanks for this package and this is very useful but, I would like to send file and that part is not working..

**Comment by edelciomolina** [comment]
@dtouffut My guess is that this exception happens when there is multiples `ssh.putFile` or when `ssh.putDirectory` is used.
I had trouble with these two cases, so I fixed with Promises and changed `putDirectory` function by a recursive checking for all files using `fs` then I sent each file to `ssh.putFile` and now all works fine.
