### ISSUE TITLE
Error: All configured authentication methods failed

### ISSUE THREAD

**Issue by BigFaceCat5233** [steelbrain/node-ssh#434]
hello, everyone
here's my example

```
const fs = require('fs')
const { NodeSSH } = require('node-ssh');
const ssh = new NodeSSH();

var key = fs.readFileSync("C:/Users/deemo/.ssh/id_rsa.pub", 'utf8');
console.log(key)

ssh.connect({
    host: 'xxx.xx.xx.xx',
    username: 'xxxxx',
    password:'xxxx',
    port: 9923,
    privateKey: "C:/Users/deemo/.ssh/id_rsa",
}).then(() => {
    console.log('success')
    process.exit(0);
}).catch((err) => {
    console.log('error:', err);
    process.exit(0);
});
```
when i use my password it can work normally, but when i remove the password using the private key it would happen this mistake, i confirm that i don't have the private key path problem, there is no wrong choice is not the correct private key, and when i tried to console output it is normal, when the content of the private key in powershell directly connect to the server can be successful, i need your help,thx

the key begins in the following format is

```
-----BEGIN OPENSSH PRIVATE KEY-----
```

**Comment by steelbrain** [comment]
This should be fixed with https://github.com/steelbrain/node-ssh/pull/436 -- it's going out in the next semver-major release

**Comment by steelbrain** [comment]
Released in v13.0.0

**Comment by rswlkr** [comment]
Sorry to say that I'm still getting this error with both privateKey and privateKeyPath

**Comment by sonicparke** [comment]
I am also having this issue. Super simple example:
```js
const {NodeSSH} = require('node-ssh')

const ssh = new NodeSSH()

ssh.connect({
  host: 'xxxxx',
  username: 'xxxxx',
  privateKeyPath: '/Users/xxxxx/.ssh/id_rsa'
}).then(function() {
  return ssh.execCommand('cd /home/xxxxx/ && ls')
}).catch(function(err) {
  console.log('error: ', err)
})
```

And the error:
```sh
error:  Error: All configured authentication methods failed
    at doNextAuth (/Users/.../test-ssh/node_modules/ssh2/lib/client.js:803:21)
    at tryNextAuth (/Users/.../test-ssh/node_modules/ssh2/lib/client.js:993:7)
    at USERAUTH_FAILURE (/Users/.../test-ssh/node_modules/ssh2/lib/client.js:373:11)
    at 51 (/Users/.../test-ssh/node_modules/ssh2/lib/protocol/handlers.misc.js:337:16)
    at Protocol.onPayload (/Users/.../test-ssh/node_modules/ssh2/lib/protocol/Protocol.js:2025:10)
    at AESGCMDecipherBinding.decrypt (/Users/.../test-ssh/node_modules/ssh2/lib/protocol/crypto.js:1086:26)
    at Protocol.parsePacket [as _parse] (/Users/.../test-ssh/node_modules/ssh2/lib/protocol/Protocol.js:1994:25)
    at Protocol.parse (/Users/.../test-ssh/node_modules/ssh2/lib/protocol/Protocol.js:293:16)
    at Socket.<anonymous> (/Users/.../test-ssh/node_modules/ssh2/lib/client.js:713:21)
    at Socket.emit (events.js:400:28) {
  level: 'client-authentication'
}
```

This is a fresh new key generated with the following `ssh-keygen -t rsa -b 4096` and the pub added to `authorized_keys` on the server.
