### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by steelbrain** [steelbrain/node-ssh#8]
_From @raeesiqbal on April 12, 2015 16:45_

**Atom Version**: 0.190.0
**System**: Microsoft Windows 10 Pro Technical Preview
**Thrown From**: [autocomplete-hack](https://github.com/steelbrain/autocomplete-hack) package, v0.1.1

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At C:\Users\Raees\.atom\packages\autocomplete-hack\node_modules\node-ssh\Dist\SSH.js:82

TypeError: undefined is not a function
    at Readable.<anonymous> (C:\Users\Raees\.atom\packages\autocomplete-hack\node_modules\node-ssh\Dist\SSH.js:82:38)
    at emitOne (events.js:77:13)
    at Readable.emit (events.js:166:7)
    at Readable.read (_stream_readable.js:356:10)
    at flow (_stream_readable.js:734:26)
    at resume_ (_stream_readable.js:714:3)
    at _stream_readable.js:701:7
    at process._tickCallback (node.js:357:13)
```

### Commands

```
  6x -6:31.7 core:save (atom-text-editor.editor)
     -1:58.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:43.8 core:move-right (div.settings-view.pane-item)
     -0:03.5 core:undo (atom-text-editor.editor.is-focused)
     -0:01.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:00.5 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
Atom-Hack, v3.5.4
autocomplete-hack, v0.1.1
autocomplete-plus, v2.9.0
language-hack, v0.1.1
open-last-project, v0.4.1

# Dev
No dev packages
```

_Copied from original issue: steelbrain/AutoComplete-Hack#3_

**Comment by steelbrain** [comment]
Fixed
